import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import '../entities/measurement_session.dart';

class ExportReportUseCase {
  /// Writes a plain-text report and returns the file path.
  Future<String> call(MeasurementSession session) async {
    final content = _buildReport(session);
    final dir = await getTemporaryDirectory();
    final safeName = session.name.replaceAll(RegExp(r'[^\w\-]'), '_');
    final file = File('${dir.path}/report_$safeName.txt');
    await file.writeAsString(content);
    return file.path;
  }

  String _buildReport(MeasurementSession session) {
    final sb = StringBuffer();
    final df = DateFormat('yyyy-MM-dd HH:mm');
    final nf = NumberFormat('0.000');

    sb.writeln('THERMAL GRADIENT ANALYSIS REPORT');
    sb.writeln('=' * 50);
    sb.writeln('Session : ${session.name}');
    sb.writeln('Date    : ${df.format(session.createdAt)}');
    sb.writeln();

    _writeAnalysis(sb, 'CONDUCTOR A', session.analysisA, nf);

    if (session.analysisB != null) {
      sb.writeln();
      _writeAnalysis(sb, 'CONDUCTOR B', session.analysisB!, nf);
    }

    if (session.comparison != null) {
      final c = session.comparison!;
      sb.writeln();
      sb.writeln('COMPARISON RESULT');
      sb.writeln('-' * 40);
      sb.writeln('Status              : ${c.status.label}');
      sb.writeln(
        'Gradient deviation  : ${(c.gradientDeviation * 100).toStringAsFixed(1)} %',
      );
      sb.writeln(
        'Hotspot deviation   : ${(c.hotspotDeviation * 100).toStringAsFixed(1)} %',
      );
      sb.writeln(
        'ΔT deviation        : ${(c.deltaTDeviation * 100).toStringAsFixed(1)} %',
      );
      sb.writeln('Diagnosis           : ${c.primaryDiagnosis}');
      if (c.flags.isNotEmpty) {
        sb.writeln();
        sb.writeln('Flags:');
        for (final f in c.flags) {
          sb.writeln('  • $f');
        }
      }
    }

    sb.writeln();
    sb.writeln('─' * 50);
    sb.writeln('Generated by MijnGradientApp');
    return sb.toString();
  }

  void _writeAnalysis(
    StringBuffer sb,
    String title,
    dynamic a, // AnalysisResult
    NumberFormat nf,
  ) {
    sb.writeln(title);
    sb.writeln('-' * 40);
    sb.writeln('Conductor           : ${a.conductor.name}');
    sb.writeln('Current             : ${a.conductor.current.toStringAsFixed(1)} A');
    sb.writeln(
      'Points              : ${a.conductor.pointCount} (${a.conductor.conductorLength.toStringAsFixed(3)} m)',
    );
    sb.writeln('Max temperature     : ${a.maxTemperature.toStringAsFixed(2)} °C');
    sb.writeln('Min temperature     : ${a.minTemperature.toStringAsFixed(2)} °C');
    sb.writeln('ΔT                  : ${a.deltaT.toStringAsFixed(2)} °C');
    sb.writeln('Max |gradient|      : ${nf.format(a.maxAbsGradient)} °C/m');
    sb.writeln(
      'Normalised gradient : ${nf.format(a.normalizedGradient)} °C/m/A',
    );
    sb.writeln('Hotspot count       : ${a.hotspots.length}');
    sb.writeln(
      'Total hotspot length: ${a.totalHotspotLength.toStringAsFixed(3)} m',
    );
    sb.writeln('Smoothing           : ${a.smoothingMethod.label}');
    sb.writeln('Diagnosis           : ${a.hotspotDiagnosis}');

    if (a.hotspots.isNotEmpty) {
      sb.writeln();
      sb.writeln('Hotspots:');
      for (int i = 0; i < a.hotspots.length; i++) {
        final h = a.hotspots[i];
        sb.writeln(
          '  [${i + 1}] ${h.startPosition.toStringAsFixed(3)} m – '
          '${h.endPosition.toStringAsFixed(3)} m  '
          '(length ${h.length.toStringAsFixed(3)} m, '
          'peak ${nf.format(h.peakGradient)} °C/m)',
        );
      }
    }
  }
}
